### ISSUE TITLE
Could not find module 'tns-core-modules/ui/core/properties'

### ISSUE THREAD

**Issue by anuragd7** [rhanbIT/nativescript-bottombar#12]
Hi 
Am using angular nativescript 
tns  version 2.5.0

I get an error when i:
1.  install the bottom bar using   tns plugin add nativescript-bottombar@^2.1 
2.  add the sample code to the app.component.html and app.component.ts
3. tns run ios
 The error  I get is

file:///app/tns_modules/nativescript-bottombar/src/bottombar.js:4:27: JS ERROR Error: Could not find module 'tns-core-modules/ui/core/properties'.

**Comment by rhanbIT** [comment]
Hi @anuragd7 ,

This issue is coming from a `.js`file that was coming from the 3.x support branch which I forgot to delete for the 2.x support. Should work now

- latest version of 2.x support: `2.1.2`

**Comment by anuragd7** [comment]
Hi 
Thanks for the fix. I am now getting a different error when building in ios. Basically, the project builds but when I try to run the project in IOS I get an error 

fatal error: unexpectedly found nil while unwrapping an Optional value 

On trying to run the project in XCode there seems to be problem in the mintabbar.swift file.  Am attaching the screenshot from Xcode below.

![image](https://cloud.githubusercontent.com/assets/5083062/26498619/40c2e0a8-424d-11e7-9bc2-1d7144235b8a.png)

**Comment by rhanbIT** [comment]
Hi,

Could you do this and tell me if you still get the error: 

- `rm -rf platforms`
- `tns run ios`

Thanks :smile:

**Comment by anuragd7** [comment]
Hi 
Thanks for the suggestion. Just tried it. Still getting exactly the same error!

**Comment by anuragd7** [comment]
Hi @rhanbIT  
Any suggestions on what I could try out?
Thanks

**Comment by rhanbIT** [comment]
Hi @anuragd7 ,

Could you provide all the error output please 
thanks

**Comment by anuragd7** [comment]
Hi 
After  i execute 
`rm -rf platforms
  tns run ios`

I get the following errors in the console


`NR-MacBook-Pro:HtmlViewExample NRMac$ rm -rf platforms
NR-MacBook-Pro:HtmlViewExample NRMac$ tns run ios
Copying template files...
  ◠ Installing tns-iosInstalling  tns-ios
  ◡ Installing tns-ios/Users/NRMac/Projects/nativescript/HtmlViewExample
└── tns-ios@2.5.1 


Project successfully created.
Executing before-prepare hook from /Users/NRMac/Projects/nativescript/HtmlViewExample/hooks/before-prepare/nativescript-dev-android-snapshot.js
Executing before-prepare hook from /Users/NRMac/Projects/nativescript/HtmlViewExample/hooks/before-prepare/nativescript-dev-typescript.js
Found peer TypeScript 2.0.10
Preparing project...
Successfully prepared plugin nativescript-angular for ios.
Successfully prepared plugin nativescript-intl for ios.
Successfully prepared plugin nativescript-bottombar for ios.
Successfully prepared plugin tns-core-modules for ios.
Successfully prepared plugin tns-core-modules-widgets for ios.
Installing pods...
Analyzing dependencies
Pre-downloading: `MiniTabBar` from `https://github.com/rhanbIT/MiniTabBar.git`
Downloading dependencies
Installing MiniTabBar (1.0.2)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `HtmlViewExample.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
Project successfully prepared (ios)
Executing after-prepare hook from /Users/NRMac/Projects/nativescript/HtmlViewExample/hooks/after-prepare/nativescript-dev-android-snapshot.js
Searching for devices...
Building project...
Build settings from command line:
    ARCHS = i386 x86_64
    CODE_SIGN_IDENTITY = 
    CONFIGURATION_BUILD_DIR = /Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/build/emulator
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphonesimulator10.1
    SHARED_PRECOMPS_DIR = /Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/build/sharedpch
    TOOLCHAINS = com.apple.dt.toolchain.XcodeDefault
    VALID_ARCHS = i386 x86_64

=== BUILD TARGET MiniTabBar OF PROJECT Pods WITH CONFIGURATION Debug ===

Check dependencies

Create product structure
/bin/mkdir -p /Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/build/emulator/MiniTabBar.framework/Modules
/bin/mkdir -p /Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/build/emulator/MiniTabBar.framework/Headers

ProcessInfoPlistFile /Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/build/emulator/MiniTabBar.framework/Info.plist Target\ Support\ Files/MiniTabBar/Info.plist
    cd /Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/Pods
    builtin-infoPlistUtility /Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/Pods/Target\ Support\ Files/MiniTabBar/Info.plist -expandbuildsettings -format binary -platform iphonesimulator -o /Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/build/emulator/MiniTabBar.framework/Info.plist

CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
    cd /Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/Pods
    export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
    export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk
    export TOOLCHAINS=com.apple.dt.toolchain.XcodeDefault
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name MiniTabBar -Onone -D COCOAPODS -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk -target x86_64-apple-ios8.0 -g -module-cache-path /Users/NRMac/Library/Developer/Xcode/DerivedData/ModuleCache -Xfrontend -serialize-debugging-options -enable-testing -I /Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/build/emulator -F /Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/build/emulator -c -j4 /Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/Pods/MiniTabBar/MiniTabBar/Classes/MiniTabBar.swift /Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/Pods/MiniTabBar/MiniTabBar/Classes/MiniTabBarItemView.swift -output-file-map /Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/Objects-normal/x86_64/MiniTabBar-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/Objects-normal/x86_64/MiniTabBar.swiftmodule -Xcc -I/Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/MiniTabBar-generated-files.hmap -Xcc -I/Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/MiniTabBar-own-target-headers.hmap -Xcc -I/Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/MiniTabBar-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/MiniTabBar-project-headers.hmap -Xcc -I/Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/build/emulator/include -Xcc -I/Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/Pods/Headers/Private -Xcc -I/Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/Pods/Headers/Public -Xcc -I/Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/DerivedSources/x86_64 -Xcc -I/Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/DerivedSources -Xcc -DPOD_CONFIGURATION_DEBUG=1 -Xcc -DDEBUG=1 -Xcc -DCOCOAPODS=1 -emit-objc-header -emit-objc-header-path /Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/Objects-normal/x86_64/MiniTabBar-Swift.h -import-underlying-module -Xcc -ivfsoverlay -Xcc /Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/unextended-module-overlay.yaml -Xcc -working-directory/Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/Pods

CompileSwift normal x86_64 /Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/Pods/MiniTabBar/MiniTabBar/Classes/MiniTabBar.swift
    cd /Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c -primary-file /Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/Pods/MiniTabBar/MiniTabBar/Classes/MiniTabBar.swift /Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/Pods/MiniTabBar/MiniTabBar/Classes/MiniTabBarItemView.swift -target x86_64-apple-ios8.0 -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk -I /Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/build/emulator -F /Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/build/emulator -enable-testing -g -import-underlying-module -module-cache-path /Users/NRMac/Library/Developer/Xcode/DerivedData/ModuleCache -D COCOAPODS -serialize-debugging-options -Xcc -I/Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/MiniTabBar-generated-files.hmap -Xcc -I/Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/MiniTabBar-own-target-headers.hmap -Xcc -I/Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/MiniTabBar-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/MiniTabBar-project-headers.hmap -Xcc -I/Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/build/emulator/include -Xcc -I/Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/Pods/Headers/Private -Xcc -I/Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/Pods/Headers/Public -Xcc -I/Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/DerivedSources/x86_64 -Xcc -I/Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/DerivedSources -Xcc -DPOD_CONFIGURATION_DEBUG=1 -Xcc -DDEBUG=1 -Xcc -DCOCOAPODS=1 -Xcc -ivfsoverlay -Xcc /Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/unextended-module-overlay.yaml -Xcc -working-directory/Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/Pods -emit-module-doc-path /Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/Objects-normal/x86_64/MiniTabBar~partial.swiftdoc -Onone -module-name MiniTabBar -emit-module-path /Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/Objects-normal/x86_64/MiniTabBar~partial.swiftmodule -serialize-diagnostics-path /Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/Objects-normal/x86_64/MiniTabBar.dia -emit-dependencies-path /Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/Objects-normal/x86_64/MiniTabBar.d -emit-reference-dependencies-path /Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/Objects-normal/x86_64/MiniTabBar.swiftdeps -o /Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/Objects-normal/x86_64/MiniTabBar.o
/Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/Pods/MiniTabBar/MiniTabBar/Classes/MiniTabBar.swift:73:77: error: binary operator '!==' cannot be applied to two 'Int' operands
                if self.currentSelectedIndex != nil && self.itemViews.count !== 0 {
                                                       ~~~~~~~~~~~~~~~~~~~~ ^   ~
/Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/Pods/MiniTabBar/MiniTabBar/Classes/MiniTabBar.swift:73:77: note: expected an argument list of type '(AnyObject?, AnyObject?)'
                if self.currentSelectedIndex != nil && self.itemViews.count !== 0 {
                                                                            ^

CompileSwift normal x86_64 /Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/Pods/MiniTabBar/MiniTabBar/Classes/MiniTabBarItemView.swift
    cd /Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c /Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/Pods/MiniTabBar/MiniTabBar/Classes/MiniTabBar.swift -primary-file /Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/Pods/MiniTabBar/MiniTabBar/Classes/MiniTabBarItemView.swift -target x86_64-apple-ios8.0 -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk -I /Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/build/emulator -F /Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/build/emulator -enable-testing -g -import-underlying-module -module-cache-path /Users/NRMac/Library/Developer/Xcode/DerivedData/ModuleCache -D COCOAPODS -serialize-debugging-options -Xcc -I/Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/MiniTabBar-generated-files.hmap -Xcc -I/Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/MiniTabBar-own-target-headers.hmap -Xcc -I/Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/MiniTabBar-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/MiniTabBar-project-headers.hmap -Xcc -I/Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/build/emulator/include -Xcc -I/Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/Pods/Headers/Private -Xcc -I/Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/Pods/Headers/Public -Xcc -I/Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/DerivedSources/x86_64 -Xcc -I/Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/DerivedSources -Xcc -DPOD_CONFIGURATION_DEBUG=1 -Xcc -DDEBUG=1 -Xcc -DCOCOAPODS=1 -Xcc -ivfsoverlay -Xcc /Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/unextended-module-overlay.yaml -Xcc -working-directory/Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/Pods -emit-module-doc-path /Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/Objects-normal/x86_64/MiniTabBarItemView~partial.swiftdoc -Onone -module-name MiniTabBar -emit-module-path /Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/Objects-normal/x86_64/MiniTabBarItemView~partial.swiftmodule -serialize-diagnostics-path /Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/Objects-normal/x86_64/MiniTabBarItemView.dia -emit-dependencies-path /Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/Objects-normal/x86_64/MiniTabBarItemView.d -emit-reference-dependencies-path /Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/Objects-normal/x86_64/MiniTabBarItemView.swiftdeps -o /Users/NRMac/Library/Developer/Xcode/DerivedData/HtmlViewExample-bwofoxdmvidgztfemoskphulzkgv/Build/Intermediates/Pods.build/Debug-iphonesimulator/MiniTabBar.build/Objects-normal/x86_64/MiniTabBarItemView.o

** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64 /Users/NRMac/Projects/nativescript/HtmlViewExample/platforms/ios/Pods/MiniTabBar/MiniTabBar/Classes/MiniTabBar.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
Command xcodebuild failed with exit code 65
# run ios
`

**Comment by rhanbIT** [comment]
I updated the Swift library could you try again after deleting your platforms folder please 😄

**Comment by anuragd7** [comment]
Thanks so much. Can confirm it is running now!

**Comment by rhanbIT** [comment]
You are welcome 🛩

**Comment by anuragd7** [comment]
Hi @rhanbIT 
Just tried running the same project on android after adding the platform. Running the same project on android I am getting the  following error:


Executing before-watch hook from /Users/NRMac/Projects/nativescript/HtmlViewExample/hooks/before-watch/nativescript-dev-typescript.js
Found peer TypeScript 2.0.10
8:21:59 AM - Compilation complete. Watching for file changes.

JS: EXCEPTION: Error in app.component.html:25:23 caused by: Cannot read property 'android' of null
JS: ORIGINAL EXCEPTION: Cannot read property 'android' of null
JS: ORIGINAL STACKTRACE:
JS: TypeError: Cannot read property 'android' of null
JS:     at file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/nativescript-bottombar/src/android/bottombar.js:176:82
JS:     at Array.forEach (native)
JS:     at BottomBar.createItems (file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/nativescript-bottombar/src/android/bottombar.js:170:15)
JS:     at BottomBar._onItemsPropertyChangedSetNativeValue (file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/nativescript-bottombar/src/android/bottombar.js:165:14)
JS:     at PropertyMetadata.itemsProperty.metadata.onSetNativeValue [as _onSetNativeValue] (file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/nativescript-bottombar/src/common.js:50:15)
JS:     at BottomBar.ProxyObject._trySetNativeValue (file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/core/proxy.js:83:27)
JS:     at BottomBar.ProxyObject._onPropertyChanged (file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/core/proxy.js:46:14)
JS:     at BottomBar.View._onPropertyChanged (file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/core/view-common.js:772:45)
JS:     at BottomBar.DependencyObservable._setValueInternal (file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/core/dependency-observable.js:307:18)
JS:     at BottomBar.DependencyObservable._setValue (file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/core/dependency-observable.js:133:14)
JS: ERROR CONTEXT:
JS: [object Object]
JS: ns-renderer: ERROR BOOTSTRAPPING ANGULAR
JS: ns-renderer: Error in app.component.html:25:23 caused by: Cannot read property 'android' of null
JS: 
JS: TypeError: Cannot read property 'android' of null
JS:     at file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/nativescript-bottombar/src/android/bottombar.js:176:82
JS:     at Array.forEach (native)
JS:     at BottomBar.createItems (file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/nativescript-bottombar/src/android/bottombar.js:170:15)
JS:     at BottomBar._onItemsPropertyChangedSetNativeValue (file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/nativescript-bottombar/src/android/bottombar.js:165:14)
JS:     at PropertyMetadata.itemsProperty.metadata.onSetNativeValue [as _onSetNativeValue] (file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/nativescript-bottombar/src/common.js:50:15)
JS:     at BottomBar.ProxyObject._trySetNativeValue (file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/core/proxy.js:83:27)
JS:     at BottomBar.ProxyObject._onPropertyChanged (file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/core/proxy.js:46:14)
JS:     at BottomBar.View._onPropertyChanged (file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/core/view-common.js:772:45)
JS:     at BottomBar.DependencyObservable._setValueInternal (file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/core/dependency-observable.js:307:18)
JS:     at BottomBar.DependencyObservable._setValue (file:///data/data/org.nativescript.HtmlViewExample/files/app/tns_modules/tns-core-modules/ui/core/dependency-observable.js:133:14)

**Comment by rhanbIT** [comment]
Do you have your icons for Android in the app > App_ressources > Android folder? 

If not, the name of the ressource should match the name of the icon you're using when creating a BottomBarItem. 

And please create new issue to allow people to look for them if they have the same problem. 😄

**Comment by anuragd7** [comment]
Thanks for your input. The icons were there in the app_resources folder for all the different resolutions, it started working once i did a clean build!!

 Apologies - am creating this as a separate issue! Will close it too after creating!
